# Generated by Django 2.0.3 on 2018-06-09 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_chapter_word_num'),
        ('account', '0004_auto_20180604_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookshelf',
            name='collection_books',
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='collection_books',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
