# Generated by Django 2.0.3 on 2018-06-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_chapter_word_num'),
        ('account', '0006_auto_20180609_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('book_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('chapter_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter')),
            ],
        ),
    ]
