# Generated by Django 2.0.3 on 2018-06-23 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_updatemsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatemsg',
            name='book_updated',
        ),
        migrations.RemoveField(
            model_name='updatemsg',
            name='chapter_updated',
        ),
        migrations.DeleteModel(
            name='UpdateMsg',
        ),
    ]
