# Generated by Django 2.0.3 on 2018-06-23 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0006_auto_20180623_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('book_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('chapter_updated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Chapter')),
            ],
        ),
    ]
