# Generated by Django 2.0.3 on 2018-06-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_chapter_word_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='word_num',
        ),
    ]
