# Generated by Django 2.0.3 on 2018-06-23 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_word_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=25, unique=True, verbose_name='书名'),
        ),
    ]
