# Generated by Django 2.0.3 on 2018-06-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20180623_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='word_num',
            field=models.FloatField(default=0),
        ),
    ]
